title: <p align="center"> Sreedhar K R </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  
  <br>   
  I am learning Data Science Project. I have 18 years of IT experience and working as an Architect at CommScope.
  <br>
  </p>



theme: jekyll-theme-minimal
